Models/Livro.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MVC_EF.Exemplo1.Models;

public class Livro
{
    public int LivroID { get; set; }
    public string LivroTitulo { get; set; }
    public ushort LivroPaginas { get; set; }
    public string LivroISBN { get; set; }
    public ushort LivroAnoPublicacao { get; set; }
    public int EditoraID { get; set; }

    public Editora EditoraDoLivro { get; set; }
    public ICollection<OperacaoCompraVenda>? OperacoesDoLivro { get; set; }
    public ICollection<AutorLivro>? AutoresDoLivro { get; set; }
}

public class LivroConfiguration : IEntityTypeConfiguration<Livro>
{
    public void Configure(EntityTypeBuilder<Livro> builder)
    {
        builder.HasKey(p => p.LivroID);
        builder.Property(p => p.LivroTitulo).HasMaxLength(120).IsRequired();
        builder.Property(p => p.LivroPaginas).HasDefaultValue(0).IsRequired();
        builder.Property(p => p.LivroISBN).HasMaxLength(13).IsRequired();
        
        builder.HasOne<Editora>(p => p.EditoraDoLivro).WithMany(p => p.LivrosDaEditora);
    }
}

Controllers/LivroController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using MVC_EF.Exemplo1.Models;
using X.PagedList.Extensions;

namespace MVC_EF.Exemplo1.Controllers;

public class LivroController : Controller
{
    private readonly ApplicationDbContext _contexto;
    private readonly int _pagesize;
    
    public LivroController(ApplicationDbContext contexto, IConfiguration configuration)
    {
        _contexto = contexto;
        var pagesize = Convert.ToInt32(configuration.
            GetSection("ViewOptions").
            GetSection("PageSize").Value);
        _pagesize = pagesize > 0 ? pagesize : 10;
    }
    
    // GET
    public IActionResult Index(string? keyword, int? pagina)
    {
        IQueryable<Livro> livros = _contexto.Livros;
        if (!string.IsNullOrEmpty(keyword))
        {
            livros = livros
                .Include(p => p.EditoraDoLivro)
                .Include(p => p.AutoresDoLivro)
                .ThenInclude(p => p.Autor)
                .Where(p => p.LivroTitulo.ToUpper().Contains(keyword.ToUpper()))
                .OrderBy(p => p.LivroTitulo);
            ViewBag.keyword = keyword;
        }
        else
        {
            livros = _contexto.Livros
                .Include(p => p.EditoraDoLivro)
                .Include(p => p.AutoresDoLivro)
                .ThenInclude(p => p.Autor)
                .OrderBy(p => p.LivroTitulo);
            ViewBag.keyword = "";
        }

        var rset = livros.Select(livro => new LivroEditoraAutorListViewModel
            {
                Ano = livro.LivroAnoPublicacao,
                Editora = livro.EditoraDoLivro.EditoraNome,
                ISBN = livro.LivroISBN,
                Paginas = livro.LivroPaginas,
                Titulo = livro.LivroTitulo,
                Autores = livro.AutoresDoLivro.Any() == true ?
                    string.Join(", ", livro.AutoresDoLivro.Select(a => a.Autor.AutorNome))
                    : "Sem autores definidos",
                Id = livro.LivroID
            }).
            ToPagedList(pagina ?? 1, _pagesize);

        ViewBag.primeiro = rset.FirstItemOnPage;
        ViewBag.ultimo = rset.LastItemOnPage;
        ViewBag.total = rset.TotalItemCount;
        
        return View(rset);
    }

    public IActionResult Edit(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Index));

        var livro = _contexto.Livros
            .Include(p => p.EditoraDoLivro)
            .Include(p => p.AutoresDoLivro)
            .ThenInclude(p => p.Autor)
            .FirstOrDefault(p=> p.LivroID == id.Value);
        if (livro == null)
        {
            return NotFound();
        }

        var livroViewModel = new LivroEditoraAutorEditViewModel();
        livroViewModel.LivroID = id.Value;
        livroViewModel.Titulo = livro.LivroTitulo;
        livroViewModel.Ano = livro.LivroAnoPublicacao;
        livroViewModel.Paginas = livro.LivroPaginas;
        livroViewModel.ISBN = livro.LivroISBN;
        livroViewModel.EditoraID = livro.EditoraID;
        livroViewModel.EditoraInputSelect = new SelectList(
            _contexto.Editoras.OrderBy(p => p.EditoraNome).ToList(),
            dataValueField: "EditoraID",
            dataTextField: "EditoraNome",
            selectedValue: livro.EditoraID);

        return View(livroViewModel);
    }

    [HttpPost, ActionName("Edit")]
    public IActionResult EditConfirm(int? id, LivroEditoraAutorEditViewModel livro)
    {
        if (id == null)
            return RedirectToAction(nameof(Index));

        if (id.Value != livro.LivroID)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            var livroViewModel = new LivroEditoraAutorEditViewModel
            {
                LivroID = id.Value,
                Titulo = livro.Titulo,
                Ano = livro.Ano,
                Paginas = livro.Paginas,
                ISBN = livro.ISBN,
                EditoraID = livro.EditoraID,
                EditoraInputSelect = new SelectList(
                    _contexto.Editoras.OrderBy(p => p.EditoraNome).ToList(),
                    dataValueField: "EditoraID",
                    dataTextField: "EditoraNome",
                    selectedValue: livro.EditoraID)
            };

            return View(livroViewModel);
        }

        var livroOriginal = _contexto.Livros
            .FirstOrDefault(p => p.LivroID == livro.LivroID);

        if (livroOriginal == null)
            return NotFound();

        if (livroOriginal.LivroPaginas != livro.Paginas)
            livroOriginal.LivroPaginas = livro.Paginas;
        if (livroOriginal.LivroTitulo != livro.Titulo)
            livroOriginal.LivroTitulo = livro.Titulo;
        if (livroOriginal.LivroAnoPublicacao != livro.Ano)
            livroOriginal.LivroAnoPublicacao = livro.Ano;
        if (livroOriginal.LivroISBN != livro.ISBN)
            livroOriginal.LivroISBN = livro.ISBN;

        if (livroOriginal.EditoraID != livro.EditoraID)
        {
            var editora = _contexto.Editoras.FirstOrDefault(p => p.EditoraID == livro.EditoraID);
            if (editora == null)
                return NotFound();
            livroOriginal.EditoraID = editora.EditoraID;
        }

        if (_contexto.Entry(livroOriginal).State == EntityState.Modified)
        {
            try
            {
                _contexto.SaveChanges();
            }
            catch (DbUpdateException e)
            {
                if (!_contexto.Livros.Any(p => p.LivroID == livro.LivroID))
                    return NotFound();
                Console.WriteLine(e);
                throw;
            }
        }
        
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Create()
    {
        var novo = new LivroEditoraAutorEditViewModel();
        novo.EditoraID = 0;
        novo.EditoraInputSelect = new SelectList(
            _contexto.Editoras.OrderBy(p => p.EditoraNome).ToList(),
            dataValueField: "EditoraID",
            dataTextField: "EditoraNome");

        return View(novo);
    }

    [HttpPost, ActionName("Create")]
    public IActionResult CreatePost(LivroEditoraAutorEditViewModel livro)
    {
        if (!ModelState.IsValid)
        {
            var novo = new LivroEditoraAutorEditViewModel();
            novo.Titulo = livro.Titulo;
            novo.Ano = livro.Ano;
            novo.Paginas = livro.Paginas;
            novo.ISBN = livro.ISBN;
            novo.EditoraID = livro.EditoraID;
            novo.EditoraInputSelect = new SelectList(
                _contexto.Editoras.OrderBy(p => p.EditoraNome).ToList(),
                dataValueField: "EditoraID",
                dataTextField: "EditoraNome",
                selectedValue: livro.EditoraID);

            return View(novo);
        }

        var novoLivro = new Livro();
        novoLivro.LivroTitulo = livro.Titulo;
        novoLivro.LivroPaginas = livro.Paginas;
        novoLivro.LivroAnoPublicacao = livro.Ano;
        novoLivro.LivroISBN = livro.ISBN;
        var editora = _contexto.Editoras.FirstOrDefault(p => p.EditoraID == livro.EditoraID);
        if (editora == null)
            return NotFound();
        novoLivro.EditoraDoLivro = editora;

        _contexto.Livros.Add(novoLivro);
        
        try
        {
            _contexto.SaveChanges();
        }
        catch (DbUpdateException e)
        {
            Console.WriteLine(e);
            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Index));
        
        var livro = _contexto.Livros
            .Include(p => p.EditoraDoLivro)
            .Include(p => p.AutoresDoLivro)
            .ThenInclude(p => p.Autor)
            .FirstOrDefault(p=> p.LivroID == id.Value);
        if (livro == null)
        {
            return NotFound();
        }

        var objeto = new LivroEditoraAutorListViewModel
        {
            Id = livro.LivroID,
            Ano = livro.LivroAnoPublicacao,
            Editora = livro.EditoraDoLivro.EditoraNome,
            ISBN = livro.LivroISBN,
            Paginas = livro.LivroPaginas,
            Titulo = livro.LivroTitulo
        };
        objeto.Autores = "";
        foreach (var autor in livro.AutoresDoLivro)
        {
            objeto.Autores = objeto.Autores + autor.Autor.AutorNome + ", ";
        }

        return View(objeto);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeletePost(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Index));
        
        var livro = _contexto.Livros
            .FirstOrDefault(p=> p.LivroID == id.Value);
        if (livro == null)
        {
            return NotFound();
        }

        _contexto.Livros.Remove(livro);
        
        try
        {
            _contexto.SaveChanges();
        }
        catch (DbUpdateException e)
        {
            Console.WriteLine(e);
            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    public IActionResult AssociarAutor(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var livro = _contexto.Livros
            .Include(p => p.AutoresDoLivro)
            .ThenInclude(p => p.Autor)
            .FirstOrDefault(p => p.LivroID == id);
        if (livro == null)
        {
            return NotFound();
        }

        var autores = _contexto.Autores
            .OrderBy(a => a.AutorNome)
            .ToList();

        var viewModel = new AdicionarAutorLivroViewModel
        {
            LivroID = livro.LivroID,
            LivroTitulo = livro.LivroTitulo,
            Autores = autores,
            AutoresSelecionados = livro.AutoresDoLivro

Views/Livro/AssociarAutor.cshtml
@model AdicionarAutorLivroViewModel
@{
    Layout = "_Layout";
}
<h2>Associar autores ao livro @Model.LivroTitulo</h2>

<form asp-action="AssociarAutor" method="post">
    <input type="hidden" asp-for="LivroID" />

    <div>
        <h4>Selecione os autores:</h4>
        <ul>
            @foreach (var author in Model.Autores)
            {
                <li>
                    <input type="checkbox" name="AutoresSelecionados" value="@author.AutorID"
                           @if (Model.AutoresSelecionados != null && Model.AutoresSelecionados.Contains(author.AutorID))
                           {
                               <text>checked</text>
                           } />
                    @author.AutorNome
                </li>
            }
        </ul>
    </div>

    <button type="submit">Salvar mudanças</button>
</form>

Views/Livro/Create.cshtml
@model LivroEditoraAutorEditViewModel
@{
    ViewBag.Title = "Gerenciamento de livros";
    Layout = "_Layout";
}

<h1 class="display-6 my-5">Adicionando livro</h1>


<form asp-action="Create">
    <div class="row mb-2">
        <label asp-for="Titulo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Titulo" class="form-control" />
            <span asp-validation-for="Titulo" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Paginas" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Paginas" class="form-control" />
            <span asp-validation-for="Paginas" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Ano" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Ano" class="form-control" />
            <span asp-validation-for="Ano" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="ISBN" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ISBN" class="form-control" />
            <span asp-validation-for="ISBN" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="EditoraID" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="EditoraID" asp-items="Model.EditoraInputSelect" class="form-control form-select">
                <option value="" disabled selected>Selecione a Editora</option>
            </select>
            <span asp-validation-for="EditoraID" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a asp-action="Index" class="btn btn-secondary" role="button">Retornar ao índice</a>
</form>

Views/Livro/Delete.cshtml
@model LivroEditoraAutorListViewModel
@{
    ViewBag.Title = "Gerenciamento de livros";
    Layout = "_Layout";
}

<h1 class="display-6 my-5">Removendo livro</h1>

<form asp-action="Delete">

    <div class="row mb-2">
        <label asp-for="Titulo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Titulo" readonly class="px-3 form-control form-control-plaintext" />
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Paginas" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Paginas" readonly class="px-3 form-control form-control-plaintext" />
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Ano" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Ano" readonly class="px-3 form-control form-control-plaintext" />
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="ISBN" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ISBN" readonly class="px-3 form-control form-control-plaintext" />
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Editora" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Editora" readonly class="px-3 form-control form-control-plaintext" />
        </div>
    </div>

    <input type="submit" value="Apagar" class="btn btn-danger"/>
    <a asp-action="Index" class="btn btn-secondary" role="button">Retornar ao índice</a>
</form>

Views/Livro/Edit.cshtml
@model LivroEditoraAutorEditViewModel
@{
    ViewBag.Title = "Gerenciamento de livros";
    Layout = "_Layout";
}

<h1 class="display-6 my-5">Editando o livro</h1>

<form asp-action="Edit">
    <input type="hidden" asp-for="LivroID"  value="@Model.LivroID"></input>

    <div class="row mb-2">
        <label asp-for="Titulo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Titulo" class="form-control" />
            <span asp-validation-for="Titulo" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Paginas" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Paginas" class="form-control" />
            <span asp-validation-for="Paginas" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="Ano" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Ano" class="form-control" />
            <span asp-validation-for="Ano" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="ISBN" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ISBN" class="form-control" />
            <span asp-validation-for="ISBN" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-2">
        <label asp-for="EditoraID" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="EditoraID" asp-items="Model.EditoraInputSelect" class="form-control form-select">
                <option value="" disabled>Selecione a Editora</option>
            </select>
            <span asp-validation-for="EditoraID" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a asp-action="Index" class="btn btn-secondary" role="button">Retornar ao índice</a>
</form>

Views/Livro/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<LivroEditoraAutorListViewModel>
@{
    ViewBag.Title = "Gerenciamento de livros";
    Layout = "_Layout";
}

<h1 class="display-6 my-5">Gerenciamento de livros</h1>
@if (ViewBag.keyword != "")
{
    <div class="alert alert-success" role="alert">
        Filtrando por "@ViewBag.keyword"
    </div>
}
<form asp-action="Index">
    <div class="input-group">
        <input name="keyword" type="text" class="form-control"
               value="@ViewBag.keyword" placeholder="Filtar por..."/>
        <div class="input-group-append">
            <button class="btn btn-secondary" type="submit">Filtrar...</button>
        </div>
    </div>
</form>


<p>Cadastrar <a asp-controller="Livro" asp-action="Create">novo livro</a>?</p>

<table class="table-striped table">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(m => m[0].Titulo)</th>
        <th>@Html.DisplayNameFor(m => m[0].Ano)</th>
        <th>@Html.DisplayNameFor(m => m[0].Paginas)</th>
        <th>@Html.DisplayNameFor(m => m[0].ISBN)</th>
        <th>@Html.DisplayNameFor(m => m[0].Editora)</th>
        <th>@Html.DisplayNameFor(m => m[0].Autores)</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var livro in Model)
    {
        <tr>
            <td>@livro.Titulo</td>
            <td>@livro.Ano</td>
            <td>@livro.Paginas</td>
            <td>@livro.ISBN</td>
            <td>@livro.Editora</td>
            <td>@livro.Autores</td>
            <td>
                <a asp-controller="Livro" asp-action="Edit" asp-route-id="@livro.Id"><button type="button" class="btn btn-secondary"><i class="bi bi-pencil-square"></i></button></a>
                <a asp-controller="Livro" asp-action="Delete" asp-route-id="@livro.Id"><button type="button" class="btn btn-danger"><i class="bi bi-trash3"></i></button></a>
                <a asp-controller="Livro" asp-action="AssociarAutor" asp-route-id="@livro.Id"><button type="button" class="btn btn-primary"><i class="bi bi-people"></i></button></a>
            </td>
        </tr>
    }
    </tbody>
</table>
<p class="small">Mostrando registros de @ViewBag.primeiro até 
    @ViewBag.ultimo de um total de @ViewBag.total</p>

@Html.PagedListPager((IPagedList)Model,
    pagina => Url.Action("Index", new { pagina = pagina, keyword = @ViewBag.keyword }),
    new PagedListRenderOptions {
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" } 
    })